Yuriko/feat divide by cyclo
enricobottazzi/zk-fhe-playground pull request #4
Opened 2023-09-27 02:48 UTC by yuriko627

- renamed file names (`poly_add`, `poly_mul`, `poly_scalarmul`)with snake case 
- change constant name from `DEGREE` -> `N` in `poly_reduce`
- add `poly_divide_by_cyclo` circuit (this is the main feature)
- update README with new commands

2023-09-27 12:41 UTC, enricobottazzi requested changes

2023-09-27 12:41 UTC, enricobottazzi commented on README.md
> +env LOOKUP_BITS=8 cargo run --example poly_divide_by_cyclo -- --name poly_divide_by_cyclo -k 12 --input poly_divide_by_cyclo.in mock
The command doesn't work as there's no corresponding input file in `data`

2023-09-27 12:41 UTC, enricobottazzi commented on examples/poly_divide_by_cyclo.rs
> +// and output a polynomial divided by denominator polynomial f(x)=x^m+1 where m is a power of 2 (public output)
It actually outputs the remainder polynomial of the division

2023-09-27 12:41 UTC, enricobottazzi commented on examples/poly_divide_by_cyclo.rs
> +fn div_euclid(f: &Vec<i8>, g: &Vec<i8>) -> (Vec<i8>, Vec<i8>) {
For now it's ok. In production we should use ark library

2023-09-27 12:41 UTC, enricobottazzi commented on examples/poly_divide_by_cyclo.rs
> +    // ---- constraint check -----
Are quotient and denominator of the same degree? I think that there may be a need for padding here as well

2023-09-29 01:38 UTC, yuriko627 commented on README.md
> +env LOOKUP_BITS=8 cargo run --example poly_divide_by_cyclo -- --name poly_divide_by_cyclo -k 12 --input poly_divide_by_cyclo.in mock
ahh i forgot to push it, let me.

2023-09-29 01:57 UTC, yuriko627 commented on examples/poly_divide_by_cyclo.rs
> +// and output a polynomial divided by denominator polynomial f(x)=x^m+1 where m is a power of 2 (public output)
you're right!

2023-09-29 02:11 UTC, yuriko627 commented on examples/poly_divide_by_cyclo.rs
> +    // ---- constraint check -----
you're right, `degree(quotient)` is equal to the difference between `degree(nominator)` and `degree(denominator)` as long as `degree(nominator)` is >= `degree(denominator)` and  the test value that I used is the following:
```
    nominator : x^4 + 2x^3 + 6x^2 + 2,
    denominator : x^2 + 1,
    quotient : x^2 + 2x + 5
    remainder : -2x, -3
```
so the `degree(denominator)` and `degree(quotient)` were just coincidentally the same. 
let me add the conditional check and padding operation.

2023-09-30 18:10 UTC, enricobottazzi requested changes

2023-09-30 18:10 UTC, enricobottazzi commented on examples/poly_divide_by_cyclo.rs
> +    println!("rem_assigned: {:?}", rem_assigned);
Write a test that `rem_assigned` is equal to `out`. Note that as of now `out` from the input file is not used anywhere.

2023-10-01 15:43 UTC, yuriko627 commented on examples/poly_divide_by_cyclo.rs
> +
I changed the operand variable names to `dividend` and `divisor` from `f` and `g`. Also their types are now `u64`.
I cloned the input polynomial to `mut dividend` inside this function, just to deal with the mutability. I don't think circuit inputs should generally be mutable inside this circuit. So I just converted it to `mut`  inside this function temporarily. What do you think? 
`.is_empty()` is there just to be safe for unexpected bugs. I agree that it's not 100% necessary. I can totally remove it if that's better.

2023-10-01 17:34 UTC, enricobottazzi commented on examples/poly_divide_by_cyclo.rs
> +
Looks fine!

2023-10-02 01:35 UTC, yuriko627 commented on examples/poly_reduce.rs
> +	for i in 0..(N + 1) {
@enricobottazzi what do you mean by this? on top of line `73`-`75`?

2023-10-02 08:37 UTC, enricobottazzi requested changes

2023-10-02 08:37 UTC, enricobottazzi commented on examples/poly_divide_by_cyclo.rs
> +        let prod_mod = F::from((prod_value.value().get_lower_32() % Q as u32) as u64);
This is not a constraint, this is just a value assignment. You need to perform `div_mod` to set it as a constraint

2023-10-02 08:37 UTC, enricobottazzi commented on examples/poly_divide_by_cyclo.rs
> +    for (rem, out) in rem_assigned.iter().zip(rem_expected) {
Not solved. Test shouldn't use `get_lower_32()`. Instead compare the value `Value<F>` from `sum_assigned` to `F::from(dividend)`

2023-10-02 12:00 UTC, yuriko627 commented on examples/poly_divide_by_cyclo.rs
> +pub struct CircuitInput {
Let's discuss it in Discord.

2023-10-02 12:04 UTC, yuriko627 commented on examples/poly_divide_by_cyclo.rs
> +    let mut rem_assigned = Vec::with_capacity(input.nominator.len());
I think 0s are padded from the highest degree since I used big endian representation.

2023-10-02 12:08 UTC, yuriko627 commented on examples/poly_divide_by_cyclo.rs
> +        let result = F::from(*x as u64);
now `div_euclid` returns only positive values, converting negative values `x` as `x+Q`, so this should be solved. No negative values will be passed in the circuits.

2023-10-02 12:10 UTC, yuriko627 commented on examples/poly_divide_by_cyclo.rs
> +    let len_diff: usize = (denom_assigned.len() as i8 - quot_assigned.len() as i8).abs() as usize;
I would leave it to you if you're already working on it. Otherwise I can add it later.

2023-10-02 12:22 UTC, yuriko627 commented on examples/poly_divide_by_cyclo.rs
> +	for (sum, out) in sum_assigned.iter().zip(out_expected) {
On my end, `sum_assigned` is logging the expected value in the `value` field for all the elements. i.e. ([1, 6, 9, 6]) But I see that for values that you want to operate `get_lower_32()` on, you would wanna have a type `u32`.

2023-10-02 12:51 UTC, enricobottazzi commented on examples/poly_divide_by_cyclo.rs
> +	for (sum, out) in sum_assigned.iter().zip(out_expected) {
What I don't understand here is why you perform the `get_lower_32()` operation

2023-10-05 02:40 UTC, merged